In [22]:
import pandas as pd

In [23]:
import numpy as np

In [24]:
d=pd.date_range('20/5/2020',periods=7,freq='y')
d

DatetimeIndex(['2020-12-31', '2021-12-31', '2022-12-31', '2023-12-31',
               '2024-12-31', '2025-12-31', '2026-12-31'],
              dtype='datetime64[ns]', freq='A-DEC')

In [25]:
pd.date_range('20/5/2020','20/6/2020')

DatetimeIndex(['2020-05-20', '2020-05-21', '2020-05-22', '2020-05-23',
               '2020-05-24', '2020-05-25', '2020-05-26', '2020-05-27',
               '2020-05-28', '2020-05-29', '2020-05-30', '2020-05-31',
               '2020-06-01', '2020-06-02', '2020-06-03', '2020-06-04',
               '2020-06-05', '2020-06-06', '2020-06-07', '2020-06-08',
               '2020-06-09', '2020-06-10', '2020-06-11', '2020-06-12',
               '2020-06-13', '2020-06-14', '2020-06-15', '2020-06-16',
               '2020-06-17', '2020-06-18', '2020-06-19', '2020-06-20'],
              dtype='datetime64[ns]', freq='D')

In [26]:
np.arange(0,7,0.2)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4,
       2.6, 2.8, 3. , 3.2, 3.4, 3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8, 5. ,
       5.2, 5.4, 5.6, 5.8, 6. , 6.2, 6.4, 6.6, 6.8])

In [31]:
pd.Series(np.arange(2,9),index=pd.date_range('20/5/2020',periods=7,index))

2020-05-20    2
2020-05-21    3
2020-05-22    4
2020-05-23    5
2020-05-24    6
2020-05-25    7
2020-05-26    8
Freq: D, dtype: int32

In [33]:
s=pd.Series(['sai','lokesh',1,2,3],index=[0,1,2,3,4])
s

0       sai
1    lokesh
2         1
3         2
4         3
dtype: object

In [37]:
 s[1]

'lokesh'

In [38]:
import csv

In [43]:
f=open('datset.csv')

In [44]:
f

In [41]:
for i in f:
    print(f)

<_io.TextIOWrapper name='datset.csv' mode='r' encoding='cp1252'>
<_io.TextIOWrapper name='datset.csv' mode='r' encoding='cp1252'>
<_io.TextIOWrapper name='datset.csv' mode='r' encoding='cp1252'>
<_io.TextIOWrapper name='datset.csv' mode='r' encoding='cp1252'>

In [45]:
c=csv.reader(f)
for i in c:
    print(i)

['a', 'b', 'c', 'd', 'message']
['1', '2', '3', '4', 'hello']
['5', '6', '7', '8', 'world']
['9', '10', '11', '12', 'foo']

In [46]:
with open('datset.csv') as f:
    lines=list(csv.reader(f))

In [47]:
lines

[['a', 'b', 'c', 'd', 'message'],
 ['1', '2', '3', '4', 'hello'],
 ['5', '6', '7', '8', 'world'],
 ['9', '10', '11', '12', 'foo']]

In [51]:
a=[1,2]
b=[5,6]
d=[4,8,9]
c=list(zip(a,b,d))
c

[(1, 5, 4), (2, 6, 8)]

In [52]:
lines[1:]

[['1', '2', '3', '4', 'hello'],
 ['5', '6', '7', '8', 'world'],
 ['9', '10', '11', '12', 'foo']]

In [54]:
list1=list(zip(lines[1],lines[2],lines[3]))
list1

[('1', '5', '9'),
 ('2', '6', '10'),
 ('3', '7', '11'),
 ('4', '8', '12'),
 ('hello', 'world', 'foo')]

In [56]:
list2=list(zip(lines[0],list1))
list2

[('a', ('1', '5', '9')),
 ('b', ('2', '6', '10')),
 ('c', ('3', '7', '11')),
 ('d', ('4', '8', '12')),
 ('message', ('hello', 'world', 'foo'))]

In [58]:
a={k:v for k,v in list2}
a

{'a': ('1', '5', '9'),
 'b': ('2', '6', '10'),
 'c': ('3', '7', '11'),
 'd': ('4', '8', '12'),
 'message': ('hello', 'world', 'foo')}

In [69]:
a=pd.read_csv('datset.csv')
a

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [71]:
a.to_json('pp.json',orient='records')

In [103]:
import requests

In [106]:
url='https://www.json.org/example.html'
r=requests.get(url)

In [107]:
type(r)

requests.models.Response

In [81]:
obj=""""
{"glossary": {
        "title": "example glossary",
		"GlossDiv": {
            "title": "S",
          lossList": {
                "GlossEntry": {
             	"SortAs": "SGML",
		       "ID": "SGML",
						"GlossTerm": "Standard Generalized Markup Language",
			"Acronym": "SGML",
					"Abbrev": "ISO 8879:1986",
					"GlossDef": {
                        "para": "A meta-markup language, used to create markup languages such as DocBook.",
						"GlossSeeAlso": ["GML", "XML"]
                    },
					"GlossSee": "markup"
                }
            }
        }
    }
}"""

In [82]:
import json

In [91]:
a=pd.read_csv('C:\\Users\\sai lokesh\\Desktop\\net.csv')
a

       1             Quincy Acy   PF   24
0      2           Jordan Adams   SG   20
1      3           Steven Adams    C   21
2      4            Jeff Adrien   PF   28
3      5          Arron Afflalo   SG   29
4      5          Arron Afflalo   SG   29
5      5          Arron Afflalo   SG   29
6      6          Alexis Ajinça    C   26
7      7         Furkan Aldemir   PF   23
8      8           Cole Aldrich    C   26
9      9      LaMarcus Aldridge   PF   29
10    10            Lavoy Allen    C   25
11    11             Tony Allen   SG   33
12    12        Al-Farouq Aminu   SF   24
13    13           Lou Amundson   PF   32
14    13           Lou Amundson   PF   32
15    13           Lou Amundson   PF   32
16    14         Chris Andersen    C   36
17    15          Alan Anderson   SG   32
18    16          Kyle Anderson   SF   21
19    17          Ryan Anderson   PF   26
20    18  Giannis Antetokounmpo   SG   20
21    19        Carmelo Anthony   SF   30
22    20           Joel Anthony    C   32
23    Rk                 Player  Pos  Age
24    21             Pero Antić    C   32
25    22           Trevor Ariza   SF   29
26    23         Darrell Arthur   PF   26
27    24              Ömer Aşık    C   28
28    25          D.J. Augustin   PG   27
29    25          D.J. Augustin   PG   27
..   ...                    ...  ...  ...
644  477        Elliot Williams   SG   25
645  477        Elliot Williams   SG   25
646  477        Elliot Williams   SG   25
647  478           Lou Williams   SG   28
648  479        Marvin Williams   PF   28
649  480            Mo Williams   PG   32
650  480            Mo Williams   PG   32
651  480            Mo Williams   PG   32
652   Rk                 Player  Pos  Age
653  481        Reggie Williams   SF   28
654  482        Shawne Williams   SF   28
655  482        Shawne Williams   SF   28
656  482        Shawne Williams   SF   28
657  483            Jeff Withey    C   24
658  484           Nate Wolters   PG   23
659  484           Nate Wolters   PG   23
660  484           Nate Wolters   PG   23
661  485         Brandan Wright   PF   27
662  485         Brandan Wright   PF   27
663  485         Brandan Wright   PF   27
664  485         Brandan Wright   PF   27
665  486          Dorell Wright   SF   29
666  487            Tony Wroten   PG   21
667  488            James Young   SG   19
668  489             Nick Young   SG   29
669  490         Thaddeus Young   PF   26
670  490         Thaddeus Young   PF   26
671  490         Thaddeus Young   PF   26
672  491            Cody Zeller    C   22
673  492           Tyler Zeller    C   25

[674 rows x 4 columns]

In [86]:
a['newcolimn']=1

In [87]:
a

       1             Quincy Acy   PF   24  newcolimn
0      2           Jordan Adams   SG   20          1
1      3           Steven Adams    C   21          1
2      4            Jeff Adrien   PF   28          1
3      5          Arron Afflalo   SG   29          1
4      5          Arron Afflalo   SG   29          1
5      5          Arron Afflalo   SG   29          1
6      6          Alexis Ajinça    C   26          1
7      7         Furkan Aldemir   PF   23          1
8      8           Cole Aldrich    C   26          1
9      9      LaMarcus Aldridge   PF   29          1
10    10            Lavoy Allen    C   25          1
11    11             Tony Allen   SG   33          1
12    12        Al-Farouq Aminu   SF   24          1
13    13           Lou Amundson   PF   32          1
14    13           Lou Amundson   PF   32          1
15    13           Lou Amundson   PF   32          1
16    14         Chris Andersen    C   36          1
17    15          Alan Anderson   SG   32          1
18    16          Kyle Anderson   SF   21          1
19    17          Ryan Anderson   PF   26          1
20    18  Giannis Antetokounmpo   SG   20          1
21    19        Carmelo Anthony   SF   30          1
22    20           Joel Anthony    C   32          1
23    Rk                 Player  Pos  Age          1
24    21             Pero Antić    C   32          1
25    22           Trevor Ariza   SF   29          1
26    23         Darrell Arthur   PF   26          1
27    24              Ömer Aşık    C   28          1
28    25          D.J. Augustin   PG   27          1
29    25          D.J. Augustin   PG   27          1
..   ...                    ...  ...  ...        ...
644  477        Elliot Williams   SG   25          1
645  477        Elliot Williams   SG   25          1
646  477        Elliot Williams   SG   25          1
647  478           Lou Williams   SG   28          1
648  479        Marvin Williams   PF   28          1
649  480            Mo Williams   PG   32          1
650  480            Mo Williams   PG   32          1
651  480            Mo Williams   PG   32          1
652   Rk                 Player  Pos  Age          1
653  481        Reggie Williams   SF   28          1
654  482        Shawne Williams   SF   28          1
655  482        Shawne Williams   SF   28          1
656  482        Shawne Williams   SF   28          1
657  483            Jeff Withey    C   24          1
658  484           Nate Wolters   PG   23          1
659  484           Nate Wolters   PG   23          1
660  484           Nate Wolters   PG   23          1
661  485         Brandan Wright   PF   27          1
662  485         Brandan Wright   PF   27          1
663  485         Brandan Wright   PF   27          1
664  485         Brandan Wright   PF   27          1
665  486          Dorell Wright   SF   29          1
666  487            Tony Wroten   PG   21          1
667  488            James Young   SG   19          1
668  489             Nick Young   SG   29          1
669  490         Thaddeus Young   PF   26          1
670  490         Thaddeus Young   PF   26          1
671  490         Thaddeus Young   PF   26          1
672  491            Cody Zeller    C   22          1
673  492           Tyler Zeller    C   25          1

[674 rows x 5 columns]

In [88]:
a.head()

   1     Quincy Acy  PF  24  newcolimn
0  2   Jordan Adams  SG  20          1
1  3   Steven Adams   C  21          1
2  4    Jeff Adrien  PF  28          1
3  5  Arron Afflalo  SG  29          1
4  5  Arron Afflalo  SG  29          1

In [89]:
a

       1             Quincy Acy   PF   24  newcolimn
0      2           Jordan Adams   SG   20          1
1      3           Steven Adams    C   21          1
2      4            Jeff Adrien   PF   28          1
3      5          Arron Afflalo   SG   29          1
4      5          Arron Afflalo   SG   29          1
5      5          Arron Afflalo   SG   29          1
6      6          Alexis Ajinça    C   26          1
7      7         Furkan Aldemir   PF   23          1
8      8           Cole Aldrich    C   26          1
9      9      LaMarcus Aldridge   PF   29          1
10    10            Lavoy Allen    C   25          1
11    11             Tony Allen   SG   33          1
12    12        Al-Farouq Aminu   SF   24          1
13    13           Lou Amundson   PF   32          1
14    13           Lou Amundson   PF   32          1
15    13           Lou Amundson   PF   32          1
16    14         Chris Andersen    C   36          1
17    15          Alan Anderson   SG   32          1
18    16          Kyle Anderson   SF   21          1
19    17          Ryan Anderson   PF   26          1
20    18  Giannis Antetokounmpo   SG   20          1
21    19        Carmelo Anthony   SF   30          1
22    20           Joel Anthony    C   32          1
23    Rk                 Player  Pos  Age          1
24    21             Pero Antić    C   32          1
25    22           Trevor Ariza   SF   29          1
26    23         Darrell Arthur   PF   26          1
27    24              Ömer Aşık    C   28          1
28    25          D.J. Augustin   PG   27          1
29    25          D.J. Augustin   PG   27          1
..   ...                    ...  ...  ...        ...
644  477        Elliot Williams   SG   25          1
645  477        Elliot Williams   SG   25          1
646  477        Elliot Williams   SG   25          1
647  478           Lou Williams   SG   28          1
648  479        Marvin Williams   PF   28          1
649  480            Mo Williams   PG   32          1
650  480            Mo Williams   PG   32          1
651  480            Mo Williams   PG   32          1
652   Rk                 Player  Pos  Age          1
653  481        Reggie Williams   SF   28          1
654  482        Shawne Williams   SF   28          1
655  482        Shawne Williams   SF   28          1
656  482        Shawne Williams   SF   28          1
657  483            Jeff Withey    C   24          1
658  484           Nate Wolters   PG   23          1
659  484           Nate Wolters   PG   23          1
660  484           Nate Wolters   PG   23          1
661  485         Brandan Wright   PF   27          1
662  485         Brandan Wright   PF   27          1
663  485         Brandan Wright   PF   27          1
664  485         Brandan Wright   PF   27          1
665  486          Dorell Wright   SF   29          1
666  487            Tony Wroten   PG   21          1
667  488            James Young   SG   19          1
668  489             Nick Young   SG   29          1
669  490         Thaddeus Young   PF   26          1
670  490         Thaddeus Young   PF   26          1
671  490         Thaddeus Young   PF   26          1
672  491            Cody Zeller    C   22          1
673  492           Tyler Zeller    C   25          1

[674 rows x 5 columns]

In [101]:
a['date']=d
d

DatetimeIndex(['2020-05-31', '2020-06-30', '2020-07-31', '2020-08-31',
               '2020-09-30', '2020-10-31', '2020-11-30', '2020-12-31',
               '2021-01-31', '2021-02-28',
               ...
               '2075-09-30', '2075-10-31', '2075-11-30', '2075-12-31',
               '2076-01-31', '2076-02-29', '2076-03-31', '2076-04-30',
               '2076-05-31', '2076-06-30'],
              dtype='datetime64[ns]', length=674, freq='M')

In [97]:
d=pd.date_range('20/5/2020',periods=674,freq='m')

In [119]:
a

       1             Quincy Acy   PF   24       date
0      2           Jordan Adams   SG   20 2020-05-31
1      3           Steven Adams    C   21 2020-06-30
2      4            Jeff Adrien   PF   28 2020-07-31
3      5          Arron Afflalo   SG   29 2020-08-31
4      5          Arron Afflalo   SG   29 2020-09-30
5      5          Arron Afflalo   SG   29 2020-10-31
6      6          Alexis Ajinça    C   26 2020-11-30
7      7         Furkan Aldemir   PF   23 2020-12-31
8      8           Cole Aldrich    C   26 2021-01-31
9      9      LaMarcus Aldridge   PF   29 2021-02-28
10    10            Lavoy Allen    C   25 2021-03-31
11    11             Tony Allen   SG   33 2021-04-30
12    12        Al-Farouq Aminu   SF   24 2021-05-31
13    13           Lou Amundson   PF   32 2021-06-30
14    13           Lou Amundson   PF   32 2021-07-31
15    13           Lou Amundson   PF   32 2021-08-31
16    14         Chris Andersen    C   36 2021-09-30
17    15          Alan Anderson   SG   32 2021-10-31
18    16          Kyle Anderson   SF   21 2021-11-30
19    17          Ryan Anderson   PF   26 2021-12-31
20    18  Giannis Antetokounmpo   SG   20 2022-01-31
21    19        Carmelo Anthony   SF   30 2022-02-28
22    20           Joel Anthony    C   32 2022-03-31
23    Rk                 Player  Pos  Age 2022-04-30
24    21             Pero Antić    C   32 2022-05-31
25    22           Trevor Ariza   SF   29 2022-06-30
26    23         Darrell Arthur   PF   26 2022-07-31
27    24              Ömer Aşık    C   28 2022-08-31
28    25          D.J. Augustin   PG   27 2022-09-30
29    25          D.J. Augustin   PG   27 2022-10-31
..   ...                    ...  ...  ...        ...
644  477        Elliot Williams   SG   25 2074-01-31
645  477        Elliot Williams   SG   25 2074-02-28
646  477        Elliot Williams   SG   25 2074-03-31
647  478           Lou Williams   SG   28 2074-04-30
648  479        Marvin Williams   PF   28 2074-05-31
649  480            Mo Williams   PG   32 2074-06-30
650  480            Mo Williams   PG   32 2074-07-31
651  480            Mo Williams   PG   32 2074-08-31
652   Rk                 Player  Pos  Age 2074-09-30
653  481        Reggie Williams   SF   28 2074-10-31
654  482        Shawne Williams   SF   28 2074-11-30
655  482        Shawne Williams   SF   28 2074-12-31
656  482        Shawne Williams   SF   28 2075-01-31
657  483            Jeff Withey    C   24 2075-02-28
658  484           Nate Wolters   PG   23 2075-03-31
659  484           Nate Wolters   PG   23 2075-04-30
660  484           Nate Wolters   PG   23 2075-05-31
661  485         Brandan Wright   PF   27 2075-06-30
662  485         Brandan Wright   PF   27 2075-07-31
663  485         Brandan Wright   PF   27 2075-08-31
664  485         Brandan Wright   PF   27 2075-09-30
665  486          Dorell Wright   SF   29 2075-10-31
666  487            Tony Wroten   PG   21 2075-11-30
667  488            James Young   SG   19 2075-12-31
668  489             Nick Young   SG   29 2076-01-31
669  490         Thaddeus Young   PF   26 2076-02-29
670  490         Thaddeus Young   PF   26 2076-03-31
671  490         Thaddeus Young   PF   26 2076-04-30
672  491            Cody Zeller    C   22 2076-05-31
673  492           Tyler Zeller    C   25 2076-06-30

[674 rows x 5 columns]

In [121]:
a.dtypes

1                     object
Quincy Acy            object
PF                    object
24                    object
date          datetime64[ns]
dtype: object

In [112]:
p.to_json()

'{"User ID":{"0":15624510,"1":15810944,"2":15668575,"3":15603246,"4":15804002,"5":15728773,"6":15598044,"7":15694829,"8":15600575,"9":15727311,"10":15570769,"11":15606274,"12":15746139,"13":15704987,"14":15628972,"15":15697686,"16":15733883,"17":15617482,"18":15704583,"19":15621083,"20":15649487,"21":15736760,"22":15714658,"23":15599081,"24":15705113,"25":15631159,"26":15792818,"27":15633531,"28":15744529,"29":15669656,"30":15581198,"31":15729054,"32":15573452,"33":15776733,"34":15724858,"35":15713144,"36":15690188,"37":15689425,"38":15671766,"39":15782806,"40":15764419,"41":15591915,"42":15772798,"43":15792008,"44":15715541,"45":15639277,"46":15798850,"47":15776348,"48":15727696,"49":15793813,"50":15694395,"51":15764195,"52":15744919,"53":15671655,"54":15654901,"55":15649136,"56":15775562,"57":15807481,"58":15642885,"59":15789109,"60":15814004,"61":15673619,"62":15595135,"63":15583681,"64":15605000,"65":15718071,"66":15679760,"67":15654574,"68":15577178,"69":15595324,"70":15756932,"71":15726358,"72":15595228,"73":15782530,"74":15592877,"75":15651983,"76":15746737,"77":15774179,"78":15667265,"79":15655123,"80":15595917,"81":15668385,"82":15709476,"83":15711218,"84":15798659,"85":15663939,"86":15694946,"87":15631912,"88":15768816,"89":15682268,"90":15684801,"91":15636428,"92":15809823,"93":15699284,"94":15786993,"95":15709441,"96":15710257,"97":15582492,"98":15575694,"99":15756820,"100":15766289,"101":15593014,"102":15584545,"103":15675949,"104":15672091,"105":15801658,"106":15706185,"107":15789863,"108":15720943,"109":15697997,"110":15665416,"111":15660200,"112":15619653,"113":15773447,"114":15739160,"115":15689237,"116":15679297,"117":15591433,"118":15642725,"119":15701962,"120":15811613,"121":15741049,"122":15724423,"123":15574305,"124":15678168,"125":15697020,"126":15610801,"127":15745232,"128":15722758,"129":15792102,"130":15675185,"131":15801247,"132":15725660,"133":15638963,"134":15800061,"135":15578006,"136":15668504,"137":15687491,"138":15610403,"139":15741094,"140":15807909,"141":15666141,"142":15617134,"143":15783029,"144":15622833,"145":15746422,"146":15750839,"147":15749130,"148":15779862,"149":15767871,"150":15679651,"151":15576219,"152":15699247,"153":15619087,"154":15605327,"155":15610140,"156":15791174,"157":15602373,"158":15762605,"159":15598840,"160":15744279,"161":15670619,"162":15599533,"163":15757837,"164":15697574,"165":15578738,"166":15762228,"167":15614827,"168":15789815,"169":15579781,"170":15587013,"171":15570932,"172":15794661,"173":15581654,"174":15644296,"175":15614420,"176":15609653,"177":15594577,"178":15584114,"179":15673367,"180":15685576,"181":15774727,"182":15694288,"183":15603319,"184":15759066,"185":15814816,"186":15724402,"187":15571059,"188":15674206,"189":15715160,"190":15730448,"191":15662067,"192":15779581,"193":15662901,"194":15689751,"195":15667742,"196":15738448,"197":15680243,"198":15745083,"199":15708228,"200":15628523,"201":15708196,"202":15735549,"203":15809347,"204":15660866,"205":15766609,"206":15654230,"207":15794566,"208":15800890,"209":15697424,"210":15724536,"211":15735878,"212":15707596,"213":15657163,"214":15622478,"215":15779529,"216":15636023,"217":15582066,"218":15666675,"219":15732987,"220":15789432,"221":15663161,"222":15694879,"223":15593715,"224":15575002,"225":15622171,"226":15795224,"227":15685346,"228":15691808,"229":15721007,"230":15794253,"231":15694453,"232":15813113,"233":15614187,"234":15619407,"235":15646227,"236":15660541,"237":15753874,"238":15617877,"239":15772073,"240":15701537,"241":15736228,"242":15780572,"243":15769596,"244":15586996,"245":15722061,"246":15638003,"247":15775590,"248":15730688,"249":15753102,"250":15810075,"251":15723373,"252":15795298,"253":15584320,"254":15724161,"255":15750056,"256":15609637,"257":15794493,"258":15569641,"259":15815236,"260":15811177,"261":15680587,"262":15672821,"263":15767681,"264":15600379,"265":15801336,"266":15721592,"267":15581282,"268":15746203,"269":15583137,"270":15680752,"271":15688172,"272":15791373,"273":15589449,"274":15692819,"275":15727467,"276":15734312,"277":15764604,"278":15613014,"279":15759684,"280":15609669,"281":15685536,"282":15750447,"283":15663249,"284":15638646,"285":15734161,"286":15631070,"287":15761950,"288":15649668,"289":15713912,"290":15586757,"291":15596522,"292":15625395,"293":15760570,"294":15566689,"295":15725794,"296":15673539,"297":15705298,"298":15675791,"299":15747043,"300":15736397,"301":15678201,"302":15720745,"303":15637593,"304":15598070,"305":15787550,"306":15603942,"307":15733973,"308":15596761,"309":15652400,"310":15717893,"311":15622585,"312":15733964,"313":15753861,"314":15747097,"315":15594762,"316":15667417,"317":15684861,"318":15742204,"319":15623502,"320":15774872,"321":15611191,"322":15674331,"323":15619465,"324":15575247,"325":15695679,"326":15713463,"327":15785170,"328":15796351,"329":15639576,"330":15693264,"331":15589715,"332":15769902,"333":15587177,"334":15814553,"335":15601550,"336":15664907,"337":15612465,"338":15810800,"339":15665760,"340":15588080,"341":15776844,"342":15717560,"343":15629739,"344":15729908,"345":15716781,"346":15646936,"347":15768151,"348":15579212,"349":15721835,"350":15800515,"351":15591279,"352":15587419,"353":15750335,"354":15699619,"355":15606472,"356":15778368,"357":15671387,"358":15573926,"359":15709183,"360":15577514,"361":15778830,"362":15768072,"363":15768293,"364":15654456,"365":15807525,"366":15574372,"367":15671249,"368":15779744,"369":15624755,"370":15611430,"371":15774744,"372":15629885,"373":15708791,"374":15793890,"375":15646091,"376":15596984,"377":15800215,"378":15577806,"379":15749381,"380":15683758,"381":15670615,"382":15715622,"383":15707634,"384":15806901,"385":15775335,"386":15724150,"387":15627220,"388":15672330,"389":15668521,"390":15807837,"391":15592570,"392":15748589,"393":15635893,"394":15757632,"395":15691863,"396":15706071,"397":15654296,"398":15755018,"399":15594041},"Gender":{"0":"Male","1":"Male","2":"Female","3":"Female","4":"Male","5":"Male","6":"Female","7":"Female","8":"Male","9":"Female","10":"Female","11":"Female","12":"Male","13":"Male","14":"Male","15":"Male","16":"Male","17":"Male","18":"Male","19":"Female","20":"Male","21":"Female","22":"Male","23":"Female","24":"Male","25":"Male","26":"Male","27":"Female","28":"Male","29":"Male","30":"Male","31":"Female","32":"Female","33":"Female","34":"Male","35":"Male","36":"Female","37":"Male","38":"Female","39":"Female","40":"Female","41":"Female","42":"Male","43":"Male","44":"Female","45":"Male","46":"Male","47":"Female","48":"Male","49":"Female","50":"Female","51":"Female","52":"Female","53":"Female","54":"Female","55":"Female","56":"Female","57":"Male","58":"Male","59":"Female","60":"Male","61":"Male","62":"Female","63":"Male","64":"Female","65":"Male","66":"Male","67":"Female","68":"Female","69":"Female","70":"Male","71":"Female","72":"Female","73":"Female","74":"Male","75":"Male","76":"Male","77":"Female","78":"Female","79":"Female","80":"Male","81":"Male","82":"Male","83":"Male","84":"Female","85":"Female","86":"Male","87":"Female","88":"Male","89":"Male","90":"Male","91":"Female","92":"Male","93":"Female","94":"Female","95":"Female","96":"Female","97":"Male","98":"Male","99":"Female","100":"Male","101":"Male","102":"Female","103":"Female","104":"Female","105":"Male","106":"Female","107":"Male","108":"Male","109":"Female","110":"Female","111":"Female","112":"Male","113":"Male","114":"Male","115":"Male","116":"Male","117":"Male","118":"Male","119":"Male","120":"Female","121":"Male","122":"Female","123":"Male","124":"Female","125":"Female","126":"Male","127":"Male","128":"Male","129":"Female","130":"Male","131":"Male","132":"Male","133":"Female","134":"Female","135":"Male","136":"Female","137":"Male","138":"Female","139":"Male","140":"Male","141":"Female","142":"Male","143":"Male","144":"Female","145":"Female","146":"Female","147":"Female","148":"Male","149":"Male","150":"Female","151":"Male","152":"Male","153":"Female","154":"Male","155":"Female","156":"Male","157":"Male","158":"Male","159":"Female","160":"Male","161":"Male","162":"Female","163":"Male","164":"Female","165":"Female","166":"Female","167":"Female","168":"Male","169":"Female","170":"Male","171":"Male","172":"Female","173":"Female","174":"Female","175":"Female","176":"Female","177":"Male","178":"Male","179":"Female","180":"Male","181":"Female","182":"Female","183":"Male","184":"Female","185":"Male","186":"Female","187":"Female","188":"Male","189":"Male","190":"Male","191":"Female","192":"Male","193":"Male","194":"Male","195":"Male","196":"Female","197":"Female","198":"Male","199":"Male","200":"Male","201":"Male","202":"Female","203":"Female","204":"Female","205":"Female","206":"Female","207":"Female","208":"Female","209":"Female","210":"Female","211":"Male","212":"Female","213":"Male","214":"Male","215":"Female","216":"Male","217":"Male","218":"Female","219":"Male","220":"Female","221":"Male","222":"Male","223":"Male","224":"Female","225":"Male","226":"Female","227":"Male","228":"Female","229":"Female","230":"Female","231":"Male","232":"Male","233":"Male","234":"Female","235":"Male","236":"Male","237":"Female","238":"Female","239":"Female","240":"Male","241":"Male","242":"Female","243":"Female","244":"Female","245":"Female","246":"Female","247":"Female","248":"Male","249":"Female","250":"Female","251":"Male","252":"Female","253":"Female","254":"Female","255":"Female","256":"Female","257":"Male","258":"Female","259":"Female","260":"Female","261":"Male","262":"Female","263":"Female","264":"Male","265":"Female","266":"Male","267":"Male","268":"Female","269":"Male","270":"Female","271":"Female","272":"Male","273":"Male","274":"Female","275":"Male","276":"Male","277":"Male","278":"Female","279":"Female","280":"Female","281":"Male","282":"Male","283":"Female","284":"Male","285":"Female","286":"Female","287":"Female","288":"Male","289":"Female","290":"Male","291":"Male","292":"Male","293":"Male","294":"Female","295":"Female","296":"Male","297":"Female","298":"Male","299":"Male","300":"Female","301":"Male","302":"Female","303":"Male","304":"Female","305":"Male","306":"Female","307":"Female","308":"Male","309":"Female","310":"Female","311":"Male","312":"Female","313":"Female","314":"Female","315":"Female","316":"Female","317":"Male","318":"Male","319":"Male","320":"Female","321":"Female","322":"Male","323":"Female","324":"Female","325":"Female","326":"Male","327":"Female","328":"Male","329":"Female","330":"Male","331":"Female","332":"Male","333":"Male","334":"Male","335":"Female","336":"Male","337":"Male","338":"Female","339":"Male","340":"Female","341":"Male","342":"Female","343":"Female","344":"Male","345":"Female","346":"Male","347":"Female","348":"Male","349":"Male","350":"Female","351":"Male","352":"Female","353":"Female","354":"Male","355":"Male","356":"Male","357":"Female","358":"Male","359":"Male","360":"Male","361":"Female","362":"Female","363":"Female","364":"Male","365":"Female","366":"Female","367":"Male","368":"Male","369":"Female","370":"Female","371":"Male","372":"Female","373":"Male","374":"Female","375":"Female","376":"Female","377":"Female","378":"Male","379":"Female","380":"Male","381":"Male","382":"Female","383":"Male","384":"Female","385":"Male","386":"Female","387":"Male","388":"Male","389":"Female","390":"Male","391":"Male","392":"Female","393":"Male","394":"Female","395":"Female","396":"Male","397":"Female","398":"Male","399":"Female"},"Age":{"0":19,"1":35,"2":26,"3":27,"4":19,"5":27,"6":27,"7":32,"8":25,"9":35,"10":26,"11":26,"12":20,"13":32,"14":18,"15":29,"16":47,"17":45,"18":46,"19":48,"20":45,"21":47,"22":48,"23":45,"24":46,"25":47,"26":49,"27":47,"28":29,"29":31,"30":31,"31":27,"32":21,"33":28,"34":27,"35":35,"36":33,"37":30,"38":26,"39":27,"40":27,"41":33,"42":35,"43":30,"44":28,"45":23,"46":25,"47":27,"48":30,"49":31,"50":24,"51":18,"52":29,"53":35,"54":27,"55":24,"56":23,"57":28,"58":22,"59":32,"60":27,"61":25,"62":23,"63":32,"64":59,"65":24,"66":24,"67":23,"68":22,"69":31,"70":25,"71":24,"72":20,"73":33,"74":32,"75":34,"76":18,"77":22,"78":28,"79":26,"80":30,"81":39,"82":20,"83":35,"84":30,"85":31,"86":24,"87":28,"88":26,"89":35,"90":22,"91":30,"92":26,"93":29,"94":29,"95":35,"96":35,"97":28,"98":35,"99":28,"100":27,"101":28,"102":32,"103":33,"104":19,"105":21,"106":26,"107":27,"108":26,"109":38,"110":39,"111":37,"112":38,"113":37,"114":42,"115":40,"116":35,"117":36,"118":40,"119":41,"120":36,"121":37,"122":40,"123":35,"124":41,"125":39,"126":42,"127":26,"128":30,"129":26,"130":31,"131":33,"132":30,"133":21,"134":28,"135":23,"136":20,"137":30,"138":28,"139":19,"140":19,"141":18,"142":35,"143":30,"144":34,"145":24,"146":27,"147":41,"148":29,"149":20,"150":26,"151":41,"152":31,"153":36,"154":40,"155":31,"156":46,"157":29,"158":26,"159":32,"160":32,"161":25,"162":37,"163":35,"164":33,"165":18,"166":22,"167":35,"168":29,"169":29,"170":21,"171":34,"172":26,"173":34,"174":34,"175":23,"176":35,"177":25,"178":24,"179":31,"180":26,"181":31,"182":32,"183":33,"184":33,"185":31,"186":20,"187":33,"188":35,"189":28,"190":24,"191":19,"192":29,"193":19,"194":28,"195":34,"196":30,"197":20,"198":26,"199":35,"200":35,"201":49,"202":39,"203":41,"204":58,"205":47,"206":55,"207":52,"208":40,"209":46,"210":48,"211":52,"212":59,"213":35,"214":47,"215":60,"216":49,"217":40,"218":46,"219":59,"220":41,"221":35,"222":37,"223":60,"224":35,"225":37,"226":36,"227":56,"228":40,"229":42,"230":35,"231":39,"232":40,"233":49,"234":38,"235":46,"236":40,"237":37,"238":46,"239":53,"240":42,"241":38,"242":50,"243":56,"244":41,"245":51,"246":35,"247":57,"248":41,"249":35,"250":44,"251":37,"252":48,"253":37,"254":50,"255":52,"256":41,"257":40,"258":58,"259":45,"260":35,"261":36,"262":55,"263":35,"264":48,"265":42,"266":40,"267":37,"268":47,"269":40,"270":43,"271":59,"272":60,"273":39,"274":57,"275":57,"276":38,"277":49,"278":52,"279":50,"280":59,"281":35,"282":37,"283":52,"284":48,"285":37,"286":37,"287":48,"288":41,"289":37,"290":39,"291":49,"292":55,"293":37,"294":35,"295":36,"296":42,"297":43,"298":45,"299":46,"300":58,"301":48,"302":37,"303":37,"304":40,"305":42,"306":51,"307":47,"308":36,"309":38,"310":42,"311":39,"312":38,"313":49,"314":39,"315":39,"316":54,"317":35,"318":45,"319":36,"320":52,"321":53,"322":41,"323":48,"324":48,"325":41,"326":41,"327":42,"328":36,"329":47,"330":38,"331":48,"332":42,"333":40,"334":57,"335":36,"336":58,"337":35,"338":38,"339":39,"340":53,"341":35,"342":38,"343":47,"344":47,"345":41,"346":53,"347":54,"348":39,"349":38,"350":38,"351":37,"352":42,"353":37,"354":36,"355":60,"356":54,"357":41,"358":40,"359":42,"360":43,"361":53,"362":47,"363":42,"364":42,"365":59,"366":58,"367":46,"368":38,"369":54,"370":60,"371":60,"372":39,"373":59,"374":37,"375":46,"376":46,"377":42,"378":41,"379":58,"380":42,"381":48,"382":44,"383":49,"384":57,"385":56,"386":49,"387":39,"388":47,"389":48,"390":48,"391":47,"392":45,"393":60,"394":39,"395":46,"396":51,"397":50,"398":36,"399":49},"EstimatedSalary":{"0":19000,"1":20000,"2":43000,"3":57000,"4":76000,"5":58000,"6":84000,"7":150000,"8":33000,"9":65000,"10":80000,"11":52000,"12":86000,"13":18000,"14":82000,"15":80000,"16":25000,"17":26000,"18":28000,"19":29000,"20":22000,"21":49000,"22":41000,"23":22000,"24":23000,"25":20000,"26":28000,"27":30000,"28":43000,"29":18000,"30":74000,"31":137000,"32":16000,"33":44000,"34":90000,"35":27000,"36":28000,"37":49000,"38":72000,"39":31000,"40":17000,"41":51000,"42":108000,"43":15000,"44":84000,"45":20000,"46":79000,"47":54000,"48":135000,"49":89000,"50":32000,"51":44000,"52":83000,"53":23000,"54":58000,"55":55000,"56":48000,"57":79000,"58":18000,"59":117000,"60":20000,"61":87000,"62":66000,"63":120000,"64":83000,"65":58000,"66":19000,"67":82000,"68":63000,"69":68000,"70":80000,"71":27000,"72":23000,"73":113000,"74":18000,"75":112000,"76":52000,"77":27000,"78":87000,"79":17000,"80":80000,"81":42000,"82":49000,"83":88000,"84":62000,"85":118000,"86":55000,"87":85000,"88":81000,"89":50000,"90":81000,"91":116000,"92":15000,"93":28000,"94":83000,"95":44000,"96":25000,"97":123000,"98":73000,"99":37000,"100":88000,"101":59000,"102":86000,"103":149000,"104":21000,"105":72000,"106":35000,"107":89000,"108":86000,"109":80000,"110":71000,"111":71000,"112":61000,"113":55000,"114":80000,"115":57000,"116":75000,"117":52000,"118":59000,"119":59000,"120":75000,"121":72000,"122":75000,"123":53000,"124":51000,"125":61000,"126":65000,"127":32000,"128":17000,"129":84000,"130":58000,"131":31000,"132":87000,"133":68000,"134":55000,"135":63000,"136":82000,"137":107000,"138":59000,"139":25000,"140":85000,"141":68000,"142":59000,"143":89000,"144":25000,"145":89000,"146":96000,"147":30000,"148":61000,"149":74000,"150":15000,"151":45000,"152":76000,"153":50000,"154":47000,"155":15000,"156":59000,"157":75000,"158":30000,"159":135000,"160":100000,"161":90000,"162":33000,"163":38000,"164":69000,"165":86000,"166":55000,"167":71000,"168":148000,"169":47000,"170":88000,"171":115000,"172":118000,"173":43000,"174":72000,"175":28000,"176":47000,"177":22000,"178":23000,"179":34000,"180":16000,"181":71000,"182":117000,"183":43000,"184":60000,"185":66000,"186":82000,"187":41000,"188":72000,"189":32000,"190":84000,"191":26000,"192":43000,"193":70000,"194":89000,"195":43000,"196":79000,"197":36000,"198":80000,"199":22000,"200":39000,"201":74000,"202":134000,"203":71000,"204":101000,"205":47000,"206":130000,"207":114000,"208":142000,"209":22000,"210":96000,"211":150000,"212":42000,"213":58000,"214":43000,"215":108000,"216":65000,"217":78000,"218":96000,"219":143000,"220":80000,"221":91000,"222":144000,"223":102000,"224":60000,"225":53000,"226":126000,"227":133000,"228":72000,"229":80000,"230":147000,"231":42000,"232":107000,"233":86000,"234":112000,"235":79000,"236":57000,"237":80000,"238":82000,"239":143000,"240":149000,"241":59000,"242":88000,"243":104000,"244":72000,"245":146000,"246":50000,"247":122000,"248":52000,"249":97000,"250":39000,"251":52000,"252":134000,"253":146000,"254":44000,"255":90000,"256":72000,"257":57000,"258":95000,"259":131000,"260":77000,"261":144000,"262":125000,"263":72000,"264":90000,"265":108000,"266":75000,"267":74000,"268":144000,"269":61000,"270":133000,"271":76000,"272":42000,"273":106000,"274":26000,"275":74000,"276":71000,"277":88000,"278":38000,"279":36000,"280":88000,"281":61000,"282":70000,"283":21000,"284":141000,"285":93000,"286":62000,"287":138000,"288":79000,"289":78000,"290":134000,"291":89000,"292":39000,"293":77000,"294":57000,"295":63000,"296":73000,"297":112000,"298":79000,"299":117000,"300":38000,"301":74000,"302":137000,"303":79000,"304":60000,"305":54000,"306":134000,"307":113000,"308":125000,"309":50000,"310":70000,"311":96000,"312":50000,"313":141000,"314":79000,"315":75000,"316":104000,"317":55000,"318":32000,"319":60000,"320":138000,"321":82000,"322":52000,"323":30000,"324":131000,"325":60000,"326":72000,"327":75000,"328":118000,"329":107000,"330":51000,"331":119000,"332":65000,"333":65000,"334":60000,"335":54000,"336":144000,"337":79000,"338":55000,"339":122000,"340":104000,"341":75000,"342":65000,"343":51000,"344":105000,"345":63000,"346":72000,"347":108000,"348":77000,"349":61000,"350":113000,"351":75000,"352":90000,"353":57000,"354":99000,"355":34000,"356":70000,"357":72000,"358":71000,"359":54000,"360":129000,"361":34000,"362":50000,"363":79000,"364":104000,"365":29000,"366":47000,"367":88000,"368":71000,"369":26000,"370":46000,"371":83000,"372":73000,"373":130000,"374":80000,"375":32000,"376":74000,"377":53000,"378":87000,"379":23000,"380":64000,"381":33000,"382":139000,"383":28000,"384":33000,"385":60000,"386":39000,"387":71000,"388":34000,"389":35000,"390":33000,"391":23000,"392":45000,"393":42000,"394":59000,"395":41000,"396":23000,"397":20000,"398":33000,"399":36000},"Purchased":{"0":0,"1":0,"2":0,"3":0,"4":0,"5":0,"6":0,"7":1,"8":0,"9":0,"10":0,"11":0,"12":0,"13":0,"14":0,"15":0,"16":1,"17":1,"18":1,"19":1,"20":1,"21":1,"22":1,"23":1,"24":1,"25":1,"26":1,"27":1,"28":0,"29":0,"30":0,"31":1,"32":0,"33":0,"34":0,"35":0,"36":0,"37":0,"38":0,"39":0,"40":0,"41":0,"42":0,"

In [110]:
p=pd.read_csv(r'C:\Users\sai lokesh\Desktop\Social_Network_Ads.csv')

In [152]:
ds=pd.read_html('https://communities.sas.com/t5/General-SAS-Programming/Create-New-Dataset-using-only-specific-dates-rows/td-p/434326')

In [137]:
ds[0].

             0   1
0         Date  aa
1   1990-02-02  23
2   1990-02-07  45
3   1990-02-13  56
4   1990-02-28   7
5   1990-03-12   8
6   1990-03-13   8
7   1990-03-16   9
8   1990-03-19  55
9   1990-03-23  78
10  1990-04-03  90
11  1990-04-23  76
12  1990-05-01   6
13  1990-05-11   4
14  1990-05-15  33
15  1990-05-25  34
16  1990-05-30  12

In [138]:
new_header=ds[0].iloc[0]
ds[0]=ds[0][1:]
ds[0].columns=new_header

In [139]:
ds[0]

0         Date  aa
1   1990-02-02  23
2   1990-02-07  45
3   1990-02-13  56
4   1990-02-28   7
5   1990-03-12   8
6   1990-03-13   8
7   1990-03-16   9
8   1990-03-19  55
9   1990-03-23  78
10  1990-04-03  90
11  1990-04-23  76
12  1990-05-01   6
13  1990-05-11   4
14  1990-05-15  33
15  1990-05-25  34
16  1990-05-30  12

In [142]:
d=pd.to_datetime(ds[0]['Date'])

In [143]:
d

1    1990-02-02
2    1990-02-07
3    1990-02-13
4    1990-02-28
5    1990-03-12
6    1990-03-13
7    1990-03-16
8    1990-03-19
9    1990-03-23
10   1990-04-03
11   1990-04-23
12   1990-05-01
13   1990-05-11
14   1990-05-15
15   1990-05-25
16   1990-05-30
Name: Date, dtype: datetime64[ns]

In [144]:
ds[0]['Date']=d

C:\Users\sai lokesh\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [145]:
ds[0]

0        Date  aa
1  1990-02-02  23
2  1990-02-07  45
3  1990-02-13  56
4  1990-02-28   7
5  1990-03-12   8
6  1990-03-13   8
7  1990-03-16   9
8  1990-03-19  55
9  1990-03-23  78
10 1990-04-03  90
11 1990-04-23  76
12 1990-05-01   6
13 1990-05-11   4
14 1990-05-15  33
15 1990-05-25  34
16 1990-05-30  12

In [146]:
ds[0].dtypes

0
Date    datetime64[ns]
aa              object
dtype: object

In [148]:
d.dt.year.value_counts()

1990    16
Name: Date, dtype: int64

In [149]:
ds[0].shape

(16, 2)

In [150]:
ds[0].index

RangeIndex(start=1, stop=17, step=1)